[project]
name = "kosi-flood-predictor"
version = "0.1.0"
requires-python = ">=3.13,<3.14"
dependencies = [
    "fastapi[standard]==0.141.1",
    "scikit-learn==1.9.1",
    "joblib==1.6.0",
    "numpy==2.5.3",
    "pandas==3.0.6",
    "pyarrow==25.0.1"
]

[tool.setuptools]
py-modules = []

[tool.fastapi]
entrypoint = "backend.main:app"